import { Fragment } from "react"
import Head from "next/head"
import Image from "next/image"
import * as fs from "fs"
import path from "path"
import matter from "gray-matter"
import { NextPage } from "next"
import Link from "next/link"

const Posts: NextPage = ({ posts }: any) => {
    return (
        <Fragment>
            <div>
                <Head>
                    <title>MDX - Posts</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div style={{ width: "100%", padding: "40px" }}>
                    <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gridGap: "20px" }}>
                        {posts.map((post: any, idx: number) => (
                            <div key={idx}>
                                <div style={{ position: "relative", width: "100%", height: "220px" }}>
                                    <Image src={post.frontMatter.cover} style={{ borderRadius: "16px" }} objectFit="cover" layout="fill" alt={post.frontMatter.title} />
                                </div>
                                <h1>{post.frontMatter.title}</h1>
                                <p>{post.frontMatter.description}</p>
                                <Link href={`/posts/${post.slug}`}>
                                    <button className='detail-button'>Details</button>
                                </Link>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </Fragment>
    )
}

export async function getStaticProps() {
    const files = fs.readdirSync(path.join("md", "posts"))

    const posts = files.map((filename) => {
        const slug = filename.replace(".mdx", "")

        const markdownWithMeta = fs.readFileSync(path.join("md", "posts", filename), "utf-8")

        const { data: frontMatter } = matter(markdownWithMeta)

        return {
            slug,
            frontMatter
        }
    })

    console.log(posts)

    return {
        props: {
            posts
        }
    }
}

export default Posts