import { Fragment } from "react"
import Head from "next/head"
import Image from "next/image"
import * as fs from "fs"
import path from "path"
import matter from "gray-matter"
import { NextPage } from "next"
import Link from "next/link"
import PageLayouts from "@layouts/PageLayouts"

const Posts: NextPage = ({ posts }: any) => {
    return (
        <Fragment>
            <div>
                <Head>
                    <title>MDX - Posts</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="w-full max-w-[1440px] mx-auto px-6 md:px-24 py-4">
                    <PageLayouts>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                            {posts.map((post: any, idx: number) => (
                                <div key={idx} className="p-4 rounded-2xl bg-neutral-10">
                                    <div className="w-full h-[220px] relative">
                                        <h3 className="font-gilroy-semibold text-sm text-primary-pressed bg-neutral-10 rounded-xl border-none py-2 px-4 absolute top-2 left-2 z-20">{post.frontMatter.category}</h3>
                                        <Image src={post.frontMatter.cover} className="rounded-2xl" objectFit="cover" layout="fill" alt={post.frontMatter.title} />
                                    </div>
                                    <h1 className="font-gilroy-bold text-2xl mt-4 mb-2">{post.frontMatter.title}</h1>
                                    <p className="font-gilroy-normal text-sm mb-2 text-neutral-60">{post.frontMatter.description}</p>
                                    <Link href={`/posts/${post.slug}`}>
                                        <button className='py-3 px-6 mt-4 rounded-xl text-neutral-10 font-gilroy-medium text-md bg-primary-main'>Details</button>
                                    </Link>
                                </div>
                            ))}
                        </div>
                    </PageLayouts>
                </div>
            </div>
        </Fragment>
    )
}

export async function getStaticProps() {
    const files = fs.readdirSync(path.join("md", "posts"))

    const posts = files.map((filename) => {
        const slug = filename.replace(".mdx", "")

        const markdownWithMeta = fs.readFileSync(path.join("md", "posts", filename), "utf-8")

        const { data: frontMatter } = matter(markdownWithMeta)

        return {
            slug,
            frontMatter
        }
    })

    console.log(posts)

    return {
        props: {
            posts
        }
    }
}

export default Posts