import PageLayouts from "@layouts/PageLayouts"
import type { NextPage } from "next"
import Head from "next/head"
import { Fragment } from "react"

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>MDX - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full px-6 md:px-24 py-10">
        <PageLayouts></PageLayouts>
      </div>
    </Fragment>
  )
}

export default Home
