import type { NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>MDX - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ textAlign: "center", marginTop: "20px" }}>Next.js + MDX</h1>
    </Fragment>
  )
}

export default Home
